// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBomHgt1_8dSpyPm0GTmXo16N7__kmUnU',
    appId: '1:792057533830:web:aa47fb453d5f1de4664807',
    messagingSenderId: '792057533830',
    projectId: 'deshuung',
    authDomain: 'deshuung.firebaseapp.com',
    storageBucket: 'deshuung.firebasestorage.app',
    measurementId: 'G-6TMG89XQVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChoUPR08A0oUWBq18X2bfZBOqlQbgw0zQ',
    appId: '1:792057533830:android:069e6db14e940bb6664807',
    messagingSenderId: '792057533830',
    projectId: 'deshuung',
    storageBucket: 'deshuung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmTwlzyDuaF113S7xif6_TIjS6cSq6Jw8',
    appId: '1:792057533830:ios:ec34d3531283c90e664807',
    messagingSenderId: '792057533830',
    projectId: 'deshuung',
    storageBucket: 'deshuung.firebasestorage.app',
    iosBundleId: 'com.example.deshuung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmTwlzyDuaF113S7xif6_TIjS6cSq6Jw8',
    appId: '1:792057533830:ios:ec34d3531283c90e664807',
    messagingSenderId: '792057533830',
    projectId: 'deshuung',
    storageBucket: 'deshuung.firebasestorage.app',
    iosBundleId: 'com.example.deshuung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBomHgt1_8dSpyPm0GTmXo16N7__kmUnU',
    appId: '1:792057533830:web:424e5a7e101389b7664807',
    messagingSenderId: '792057533830',
    projectId: 'deshuung',
    authDomain: 'deshuung.firebaseapp.com',
    storageBucket: 'deshuung.firebasestorage.app',
    measurementId: 'G-Y8FPFZ563Y',
  );
}
